import type { Metadata } from 'next';
import '@/styles/globals.css';
import Sidebar from '../../views/profile/components/Sidebar';

export const metadata: Metadata = {
  title: 'Reservation app',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex">
      <Sidebar />
      <div className="ml-[150px] flex-1">{children}</div>
    </div>
  );
}
