export interface Country {
  isoCode: string;
  name: string;
  phoneCode: string;
}

export const countries: Country[] = [
  { isoCode: "AF", name: "Afghanistan", phoneCode: "+93" },
  { isoCode: "AL", name: "Albania", phoneCode: "+355" },
  { isoCode: "DZ", name: "Algeria", phoneCode: "+213" },
  { isoCode: "AS", name: "American Samoa", phoneCode: "+1-684" },
  { isoCode: "AD", name: "Andorra", phoneCode: "+376" },
  { isoCode: "AO", name: "Angola", phoneCode: "+244" },
  { isoCode: "AI", name: "Anguilla", phoneCode: "+1-264" },
  { isoCode: "AQ", name: "Antarctica", phoneCode: "+672" }, // No tiene código telefónico
  { isoCode: "AG", name: "Antigua and Barbuda", phoneCode: "+1-268" },
  { isoCode: "AR", name: "Argentina", phoneCode: "+54" },
  { isoCode: "AM", name: "Armenia", phoneCode: "+374" },
  { isoCode: "AW", name: "Aruba", phoneCode: "+297" },
  { isoCode: "AU", name: "Australia", phoneCode: "+61" },
  { isoCode: "AT", name: "Austria", phoneCode: "+43" },
  { isoCode: "AZ", name: "Azerbaijan", phoneCode: "+994" },
  { isoCode: "BS", name: "Bahamas", phoneCode: "+1-242" },
  { isoCode: "BH", name: "Bahrain", phoneCode: "+973" },
  { isoCode: "BD", name: "Bangladesh", phoneCode: "+880" },
  { isoCode: "BB", name: "Barbados", phoneCode: "+1-246" },
  { isoCode: "BY", name: "Belarus", phoneCode: "+375" },
  { isoCode: "BE", name: "Belgium", phoneCode: "+32" },
  { isoCode: "BZ", name: "Belize", phoneCode: "+501" },
  { isoCode: "BJ", name: "Benin", phoneCode: "+229" },
  { isoCode: "BM", name: "Bermuda", phoneCode: "+1-441" },
  { isoCode: "BT", name: "Bhutan", phoneCode: "+975" },
  { isoCode: "BO", name: "Bolivia", phoneCode: "+591" },
  { isoCode: "BA", name: "Bosnia and Herzegovina", phoneCode: "+387" },
  { isoCode: "BW", name: "Botswana", phoneCode: "+267" },
  { isoCode: "BR", name: "Brazil", phoneCode: "+55" },
  { isoCode: "IO", name: "British Indian Ocean Territory", phoneCode: "+246" },
  { isoCode: "VG", name: "British Virgin Islands", phoneCode: "+1-284" },
  { isoCode: "BN", name: "Brunei", phoneCode: "+673" },
  { isoCode: "BG", name: "Bulgaria", phoneCode: "+359" },
  { isoCode: "BF", name: "Burkina Faso", phoneCode: "+226" },
  { isoCode: "BI", name: "Burundi", phoneCode: "+257" },
  { isoCode: "KH", name: "Cambodia", phoneCode: "+855" },
  { isoCode: "CM", name: "Cameroon", phoneCode: "+237" },
  { isoCode: "CA", name: "Canada", phoneCode: "+1" },
  { isoCode: "CV", name: "Cape Verde", phoneCode: "+238" },
  { isoCode: "KY", name: "Cayman Islands", phoneCode: "+1-345" },
  { isoCode: "CF", name: "Central African Republic", phoneCode: "+236" },
  { isoCode: "TD", name: "Chad", phoneCode: "+235" },
  { isoCode: "CL", name: "Chile", phoneCode: "+56" },
  { isoCode: "CN", name: "China", phoneCode: "+86" },
  { isoCode: "CX", name: "Christmas Island", phoneCode: "+61" },
  { isoCode: "CC", name: "Cocos Islands", phoneCode: "+61" },
  { isoCode: "CO", name: "Colombia", phoneCode: "+57" },
  { isoCode: "KM", name: "Comoros", phoneCode: "+269" },
  { isoCode: "CK", name: "Cook Islands", phoneCode: "+682" },
  { isoCode: "CR", name: "Costa Rica", phoneCode: "+506" },
  { isoCode: "HR", name: "Croatia", phoneCode: "+385" },
  { isoCode: "CU", name: "Cuba", phoneCode: "+53" },
  { isoCode: "CW", name: "Curacao", phoneCode: "+599" },
  { isoCode: "CY", name: "Cyprus", phoneCode: "+357" },
  { isoCode: "CZ", name: "Czech Republic", phoneCode: "+420" },
  { isoCode: "CD", name: "Democratic Republic of the Congo", phoneCode: "+243" },
  { isoCode: "DK", name: "Denmark", phoneCode: "+45" },
  { isoCode: "DJ", name: "Djibouti", phoneCode: "+253" },
  { isoCode: "DM", name: "Dominica", phoneCode: "+1-767" },
  { isoCode: "DO", name: "Dominican Republic", phoneCode: "+1-809, +1-829, +1-849" },
  { isoCode: "TL", name: "East Timor", phoneCode: "+670" },
  { isoCode: "EC", name: "Ecuador", phoneCode: "+593" },
  { isoCode: "EG", name: "Egypt", phoneCode: "+20" },
  { isoCode: "SV", name: "El Salvador", phoneCode: "+503" },
  { isoCode: "GQ", name: "Equatorial Guinea", phoneCode: "+240" },
  { isoCode: "ER", name: "Eritrea", phoneCode: "+291" },
  { isoCode: "EE", name: "Estonia", phoneCode: "+372" },
  { isoCode: "ET", name: "Ethiopia", phoneCode: "+251" },
  { isoCode: "FK", name: "Falkland Islands", phoneCode: "+500" },
  { isoCode: "FO", name: "Faroe Islands", phoneCode: "+298" },
  { isoCode: "FJ", name: "Fiji", phoneCode: "+679" },
  { isoCode: "FI", name: "Finland", phoneCode: "+358" },
  { isoCode: "FR", name: "France", phoneCode: "+33" },
  { isoCode: "PF", name: "French Polynesia", phoneCode: "+689" },
  { isoCode: "GA", name: "Gabon", phoneCode: "+241" },
  { isoCode: "GM", name: "Gambia", phoneCode: "+220" },
  { isoCode: "GE", name: "Georgia", phoneCode: "+995" },
  { isoCode: "DE", name: "Germany", phoneCode: "+49" },
  { isoCode: "GH", name: "Ghana", phoneCode: "+233" },
  { isoCode: "GI", name: "Gibraltar", phoneCode: "+350" },
  { isoCode: "GR", name: "Greece", phoneCode: "+30" },
  { isoCode: "GL", name: "Greenland", phoneCode: "+299" },
  { isoCode: "GD", name: "Grenada", phoneCode: "+1-473" },
  { isoCode: "GU", name: "Guam", phoneCode: "+1-671" },
  { isoCode: "GT", name: "Guatemala", phoneCode: "+502" },
  { isoCode: "GG", name: "Guernsey", phoneCode: "+44-1481" },
  { isoCode: "GN", name: "Guinea", phoneCode: "+224" },
  { isoCode: "GW", name: "Guinea-Bissau", phoneCode: "+245" },
  { isoCode: "GY", name: "Guyana", phoneCode: "+592" },
  { isoCode: "HT", name: "Haiti", phoneCode: "+509" },
  { isoCode: "HN", name: "Honduras", phoneCode: "+504" },
  { isoCode: "HK", name: "Hong Kong", phoneCode: "+852" },
  { isoCode: "HU", name: "Hungary", phoneCode: "+36" },
  { isoCode: "IS", name: "Iceland", phoneCode: "+354" },
  { isoCode: "IN", name: "India", phoneCode: "+91" },
  { isoCode: "ID", name: "Indonesia", phoneCode: "+62" },
  { isoCode: "IR", name: "Iran", phoneCode: "+98" },
  { isoCode: "IQ", name: "Iraq", phoneCode: "+964" },
  { isoCode: "IE", name: "Ireland", phoneCode: "+353" },
  { isoCode: "IM", name: "Isle of Man", phoneCode: "+44-1624" },
  { isoCode: "IL", name: "Israel", phoneCode: "+972" },
  { isoCode: "IT", name: "Italy", phoneCode: "+39" },
  { isoCode: "CI", name: "Ivory Coast", phoneCode: "+225" },
  { isoCode: "JM", name: "Jamaica", phoneCode: "+1-876" },
  { isoCode: "JP", name: "Japan", phoneCode: "+81" },
  { isoCode: "JE", name: "Jersey", phoneCode: "+44-1534" },
  { isoCode: "JO", name: "Jordan", phoneCode: "+962" },
  { isoCode: "KZ", name: "Kazakhstan", phoneCode: "+7" },
  { isoCode: "KE", name: "Kenya", phoneCode: "+254" },
  { isoCode: "KI", name: "Kiribati", phoneCode: "+686" },
  { isoCode: "XK", name: "Kosovo", phoneCode: "+383" },
  { isoCode: "KW", name: "Kuwait", phoneCode: "+965" },
  { isoCode: "KG", name: "Kyrgyzstan", phoneCode: "+996" },
  { isoCode: "LA", name: "Laos", phoneCode: "+856" },
  { isoCode: "LV", name: "Latvia", phoneCode: "+371" },
  { isoCode: "LB", name: "Lebanon", phoneCode: "+961" },
  { isoCode: "LS", name: "Lesotho", phoneCode: "+266" },
  { isoCode: "LR", name: "Liberia", phoneCode: "+231" },
  { isoCode: "LY", name: "Libya", phoneCode: "+218" },
  { isoCode: "LI", name: "Liechtenstein", phoneCode: "+423" },
  { isoCode: "LT", name: "Lithuania", phoneCode: "+370" },
  { isoCode: "LU", name: "Luxembourg", phoneCode: "+352" },
  { isoCode: "MO", name: "Macao", phoneCode: "+853" },
  { isoCode: "MK", name: "Macedonia", phoneCode: "+389" },
  { isoCode: "MG", name: "Madagascar", phoneCode: "+261" },
  { isoCode: "MW", name: "Malawi", phoneCode: "+265" },
  { isoCode: "MY", name: "Malaysia", phoneCode: "+60" },
  { isoCode: "MV", name: "Maldives", phoneCode: "+960" },
  { isoCode: "ML", name: "Mali", phoneCode: "+223" },
  { isoCode: "MT", name: "Malta", phoneCode: "+356" },
  { isoCode: "MH", name: "Marshall Islands", phoneCode: "+692" },
  { isoCode: "MR", name: "Mauritania", phoneCode: "+222" },
  { isoCode: "MU", name: "Mauritius", phoneCode: "+230" },
  { isoCode: "YT", name: "Mayotte", phoneCode: "+262" },
  { isoCode: "MX", name: "Mexico", phoneCode: "+52" },
  { isoCode: "FM", name: "Micronesia", phoneCode: "+691" },
  { isoCode: "MD", name: "Moldova", phoneCode: "+373" },
  { isoCode: "MC", name: "Monaco", phoneCode: "+377" },
  { isoCode: "MN", name: "Mongolia", phoneCode: "+976" },
  { isoCode: "ME", name: "Montenegro", phoneCode: "+382" },
  { isoCode: "MS", name: "Montserrat", phoneCode: "+1-664" },
  { isoCode: "MA", name: "Morocco", phoneCode: "+212" },
  { isoCode: "MZ", name: "Mozambique", phoneCode: "+258" },
  { isoCode: "MM", name: "Myanmar", phoneCode: "+95" },
  { isoCode: "NA", name: "Namibia", phoneCode: "+264" },
  { isoCode: "NR", name: "Nauru", phoneCode: "+674" },
  { isoCode: "NP", name: "Nepal", phoneCode: "+977" },
  { isoCode: "NL", name: "Netherlands", phoneCode: "+31" },
  { isoCode: "AN", name: "Netherlands Antilles", phoneCode: "+599" },
  { isoCode: "NC", name: "New Caledonia", phoneCode: "+687" },
  { isoCode: "NZ", name: "New Zealand", phoneCode: "+64" },
  { isoCode: "NI", name: "Nicaragua", phoneCode: "+505" },
  { isoCode: "NE", name: "Niger", phoneCode: "+227" },
  { isoCode: "NG", name: "Nigeria", phoneCode: "+234" },
  { isoCode: "NU", name: "Niue", phoneCode: "+683" },
  { isoCode: "KP", name: "North Korea", phoneCode: "+850" },
  { isoCode: "MP", name: "Northern Mariana Islands", phoneCode: "+1-670" },
  { isoCode: "NO", name: "Norway", phoneCode: "+47" },
  { isoCode: "OM", name: "Oman", phoneCode: "+968" },
  { isoCode: "PK", name: "Pakistan", phoneCode: "+92" },
  { isoCode: "PW", name: "Palau", phoneCode: "+680" },
  { isoCode: "PS", name: "Palestinian Territory", phoneCode: "+970" },
  { isoCode: "PA", name: "Panama", phoneCode: "+507" },
  { isoCode: "PG", name: "Papua New Guinea", phoneCode: "+675" },
  { isoCode: "PY", name: "Paraguay", phoneCode: "+595" },
  { isoCode: "PE", name: "Peru", phoneCode: "+51" },
  { isoCode: "PH", name: "Philippines", phoneCode: "+63" },
  { isoCode: "PN", name: "Pitcairn", phoneCode: "+64" },
  { isoCode: "PL", name: "Poland", phoneCode: "+48" },
  { isoCode: "PT", name: "Portugal", phoneCode: "+351" },
  { isoCode: "PR", name: "Puerto Rico", phoneCode: "+1-787, +1-939" },
  { isoCode: "QA", name: "Qatar", phoneCode: "+974" },
  { isoCode: "CG", name: "Republic of the Congo", phoneCode: "+242" },
  { isoCode: "RE", name: "Reunion", phoneCode: "+262" },
  { isoCode: "RO", name: "Romania", phoneCode: "+40" },
  { isoCode: "RU", name: "Russia", phoneCode: "+7" },
  { isoCode: "RW", name: "Rwanda", phoneCode: "+250" },
  { isoCode: "BL", name: "Saint Barthelemy", phoneCode: "+590" },
  { isoCode: "SH", name: "Saint Helena", phoneCode: "+290" },
  { isoCode: "KN", name: "Saint Kitts and Nevis", phoneCode: "+1-869" },
  { isoCode: "LC", name: "Saint Lucia", phoneCode: "+1-758" },
  { isoCode: "MF", name: "Saint Martin", phoneCode: "+590" },
  { isoCode: "PM", name: "Saint Pierre and Miquelon", phoneCode: "+508" },
  { isoCode: "VC", name: "Saint Vincent and the Grenadines", phoneCode: "+1-784" },
  { isoCode: "WS", name: "Samoa", phoneCode: "+685" },
  { isoCode: "SM", name: "San Marino", phoneCode: "+378" },
  { isoCode: "ST", name: "Sao Tome and Principe", phoneCode: "+239" },
  { isoCode: "SA", name: "Saudi Arabia", phoneCode: "+966" },
  { isoCode: "SN", name: "Senegal", phoneCode: "+221" },
  { isoCode: "RS", name: "Serbia", phoneCode: "+381" },
  { isoCode: "SC", name: "Seychelles", phoneCode: "+248" },
  { isoCode: "SL", name: "Sierra Leone", phoneCode: "+232" },
  { isoCode: "SG", name: "Singapore", phoneCode: "+65" },
  { isoCode: "SX", name: "Sint Maarten", phoneCode: "+1-721" },
  { isoCode: "SK", name: "Slovakia", phoneCode: "+421" },
  { isoCode: "SI", name: "Slovenia", phoneCode: "+386" },
  { isoCode: "SB", name: "Solomon Islands", phoneCode: "+677" },
  { isoCode: "SO", name: "Somalia", phoneCode: "+252" },
  { isoCode: "ZA", name: "South Africa", phoneCode: "+27" },
  { isoCode: "KR", name: "South Korea", phoneCode: "+82" },
  { isoCode: "SS", name: "South Sudan", phoneCode: "+211" },
  { isoCode: "ES", name: "Spain", phoneCode: "+34" },
  { isoCode: "LK", name: "Sri Lanka", phoneCode: "+94" },
  { isoCode: "SD", name: "Sudan", phoneCode: "+249" },
  { isoCode: "SR", name: "Suriname", phoneCode: "+597" },
  { isoCode: "SJ", name: "Svalbard and Jan Mayen", phoneCode: "+47" },
  { isoCode: "SZ", name: "Swaziland", phoneCode: "+268" },
  { isoCode: "SE", name: "Sweden", phoneCode: "+46" },
  { isoCode: "CH", name: "Switzerland", phoneCode: "+41" },
  { isoCode: "SY", name: "Syria", phoneCode: "+963" },
  { isoCode: "TW", name: "Taiwan", phoneCode: "+886" },
  { isoCode: "TJ", name: "Tajikistan", phoneCode: "+992" },
  { isoCode: "TZ", name: "Tanzania", phoneCode: "+255" },
  { isoCode: "TH", name: "Thailand", phoneCode: "+66" },
  { isoCode: "TG", name: "Togo", phoneCode: "+228" },
  { isoCode: "TK", name: "Tokelau", phoneCode: "+690" },
  { isoCode: "TO", name: "Tonga", phoneCode: "+676" },
  { isoCode: "TT", name: "Trinidad and Tobago", phoneCode: "+1-868" },
  { isoCode: "TN", name: "Tunisia", phoneCode: "+216" },
  { isoCode: "TR", name: "Turkey", phoneCode: "+90" },
  { isoCode: "TM", name: "Turkmenistan", phoneCode: "+993" },
  { isoCode: "TC", name: "Turks and Caicos Islands", phoneCode: "+1-649" },
  { isoCode: "TV", name: "Tuvalu", phoneCode: "+688" },
  { isoCode: "VI", name: "U.S. Virgin Islands", phoneCode: "+1-340" },
  { isoCode: "UG", name: "Uganda", phoneCode: "+256" },
  { isoCode: "UA", name: "Ukraine", phoneCode: "+380" },
  { isoCode: "AE", name: "United Arab Emirates", phoneCode: "+971" },
  { isoCode: "GB", name: "United Kingdom", phoneCode: "+44" },
  { isoCode: "US", name: "United States", phoneCode: "+1" },
  { isoCode: "UY", name: "Uruguay", phoneCode: "+598" },
  { isoCode: "UZ", name: "Uzbekistan", phoneCode: "+998" },
  { isoCode: "VU", name: "Vanuatu", phoneCode: "+678" },
  { isoCode: "VA", name: "Vatican", phoneCode: "+379" },
  { isoCode: "VE", name: "Venezuela", phoneCode: "+58" },
  { isoCode: "VN", name: "Vietnam", phoneCode: "+84" },
  { isoCode: "WF", name: "Wallis and Futuna", phoneCode: "+681" },
  { isoCode: "EH", name: "Western Sahara", phoneCode: "+212" },
  { isoCode: "YE", name: "Yemen", phoneCode: "+967" },
  { isoCode: "ZM", name: "Zambia", phoneCode: "+260" },
  { isoCode: "ZW", name: "Zimbabwe", phoneCode: "+263" }
];